# 创建Secret
apiVersion: v1
kind: Secret
metadata:
  name: envhub-secret
  namespace: {{ .Values.metadata.namespace }}
type: Opaque
data:
  # base64编码的值
  ACI_ACCESS: ""
  ACI_SECRET: ""
  OSS_ACCESS_KEY_ID: ""
  OSS_ACCESS_KEY_SECRET: ""
